### ISSUE TITLE
Smarter search by author

### ISSUE THREAD

**Issue by wvengen** [medwards/free-library-on-rails#27]
Searching by author often returns books from authors that only have a matching first, middle or last name. As the collection of books grows, the noise may become larger than the actual matching author names.

This could be done by updating the search by author method to always require the last name, and to require the firstname if any is present in the book. Parsing of the search term could be done by [nameable](https://github.com/chorn/nameable) (which is already used when importing from Google books).

**Comment by medwards** [comment]
Archiving the repository.
