### ISSUE TITLE
Suggested Ubuntu version?

### ISSUE THREAD

**Issue by robinpaulson** [medwards/free-library-on-rails#4]
I tried installing this on Ubuntu 14.04 and got some errors as follows:
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke db:load_config (first_time)
*\* Invoke rails_env (first_time)
*\* Execute rails_env
*\* Execute db:load_config
*\* Execute db:migrate
==  CaseInsensitiveTags: migrating ============================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `new' for Rails::Configuration:Module/home/robin/dev/auckland_library_of_things/distributed/software/free-library-on-rails/db/migrate/011_case_insensitive_tags.rb:20:in`up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:370:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:410:in`block (2 levels) in migrate'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:410:in`block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:119:in `with_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:389:in`migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:720:in`block (2 levels) in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:775:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:775:in`block in ddl_transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/transactions.rb:208:in`transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:775:in `ddl_transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:719:in`block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:700:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:700:in`migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:570:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/migration.rb:551:in`migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.3/lib/active_record/railties/databases.rake:153:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in`call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in`each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in`invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate

I realise the versions of various pieces of software are not what you wrote it against, and before trying to debug on the latest Ubuntu, would like to know which version of the OS you used?

I tried earlier versions of rake (0.9.2.2, 10.0.3), and got errors at the bundle stage.

**Comment by medwards** [comment]
Archiving the repository.
